name: QuestApi
main: me.gritter.mcquests.api.QuestsApiPlugin
version: 1.0
api-version: 1.20
author: Wouter Gritter
commands:
  quests:
    description: Open a GUI to show your quests and their status
